name: Winamp Skin Converter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Swift version
      run: swift --version
      
    - name: Build modern converter
      run: swift build --product ModernWinampCLI
      
    - name: Test modern converter
      run: swift run ModernWinampCLI info
      
    - name: Build WinampLite
      run: |
        swiftc -o Tools/winamp-lite-ci Tools/WinampLite/main.swift -framework AppKit -framework AVFoundation
        echo "✅ WinampLite compiled successfully"
        
    - name: Test skin conversion
      run: |
        # Test with available sample skins
        if [ -f "Samples/Skins/Purple_Glow.wsz" ]; then
          swift run ModernWinampCLI convert "Samples/Skins/Purple_Glow.wsz"
        else
          echo "⚠️ Sample skins not available in CI"
        fi
        
    - name: Test legacy tools  
      run: |
        swift Scripts/WinampSimpleTest/main.swift || echo "⚠️ No sample skins in CI"
        
    - name: Verify no deprecation warnings
      run: |
        # Build with warnings treated as errors for deprecation check
        swift build --product ModernWinampCLI 2>&1 | grep -i deprecat || echo "✅ No deprecation warnings"
        
    - name: Check Metal availability
      run: |
        swift run ModernWinampCLI info | grep "Metal Device"

  test:
    runs-on: macos-15
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run all working tools
      run: |
        echo "Testing all available tools..."
        
        # Test modern CLI
        swift run ModernWinampCLI info
        
        # Test simple converter (if skins available)
        if [ -d "Samples/Skins" ] && [ "$(ls -A Samples/Skins/*.wsz 2>/dev/null)" ]; then
          ./Scripts/simple_skin_converter.swift
        else
          echo "⚠️ Sample skins not available for full test"
        fi
        
        # Verify WinampLite builds
        swiftc -o test-winamp-lite Tools/WinampLite/main.swift -framework AppKit -framework AVFoundation
        echo "✅ All tools working"
